repos:
  - repo: local
    hooks:
      - id: semantic-release
        name: Semantic Release
        entry: bash -c 'cd typescript && pnpm install && pnpm semantic-release'
        language: system
        files: ^typescript/
        pass_filenames: false
        always_run: false
        stages: [pre-push]
        verbose: true
