name: CI and Release

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

      - name: Run type checking
        run: pnpm type-check

      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Run test coverage
        run: pnpm test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/sdk/coverage/lcov.info
          flags: typescript
          name: typescript-coverage

  release:
    name: Release Packages
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-files: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for SDK changes
        id: sdk-changes
        run: |
          echo "Checking for SDK changes..."
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Previous commit: $(git rev-parse HEAD~1)"
          echo "Files changed in this commit:"
          git diff --name-only HEAD~1 HEAD
          echo "Checking if any SDK files changed..."
          if git diff --name-only HEAD~1 HEAD | grep -q "^packages/sdk/"; then
            echo "SDK files changed!"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No SDK files changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          echo "SDK changes result: ${{ steps.sdk-changes.outputs.changed }}"

      - name: Run semantic-release for SDK
        if: steps.sdk-changes.outputs.changed == 'true'
        run: |
          echo "Running semantic-release for SDK..."
          cd packages/sdk
          echo "Current directory: $(pwd)"
          echo "Package.json version: $(cat package.json | grep version)"
          CI=true pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish SDK to npm
        if: steps.sdk-changes.outputs.changed == 'true'
        run: |
          echo "Publishing SDK to npm..."
          cd packages/sdk
          echo "Current directory: $(pwd)"
          echo "Package.json version: $(cat package.json | grep version)"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
